recipes:
    mac_os_x:
      - rvm::default
attributes:
    homebrewalt:
      apps:
          - git-extras
      cask_apps:
          - slack
          - atom
          - kaleidoscope #Kaleidoscope code merge tool (paid licence)
          - alfred
          - google-chrome
          - virtualbox
          - vagrant
          - chefdk #Install Chef and tools such as knife and kitchen
          - totalterminal
          - appcode
